/**
 * Typed access to the data generated by the tools:
 *   - src/data/protocol.json  (extracted from the rippled source code)
 *   - src/data/testnet.json   (live snapshot of the XRPL Testnet: server_definitions + feature)
 *
 * Rule: for "what exists on testnet" testnet.json is authoritative; for "how it works" protocol.json is authoritative.
 */
import protocolJson from "@/data/protocol.json";
import testnetJson from "@/data/testnet.json";

export type Optionality = "required" | "optional" | "default";
export interface TxField { name: string; optionality: Optionality; mptSupported: boolean }
export interface FnAnalysis { line: number; ter: string[]; features: string[]; flags: string[]; fields: string[] }
export interface TransactorAnalysis {
  file: string;
  headerFile?: string;
  functions: Record<string, FnAnalysis>;
  allTer: string[];
  allFeatures: string[];
  allFlags: string[];
  allFields: string[];
  lines: number;
  ownerReserveFee?: boolean;
  customBaseFee?: boolean;
  ownerCountCalls?: string[];
}
export interface Transaction {
  tag: string;
  value: number;
  name: string;
  doc?: string;
  delegable: boolean;
  amendment?: string;
  privileges: string[];
  fields: TxField[];
  pseudo: boolean;
  transactor?: TransactorAnalysis;
}
export interface FlagDef { name: string; value: number; hex: string; doc?: string }
export interface LedgerEntry { tag: string; value: number; hex: string; name: string; rpcName: string; doc?: string; fields: TxField[]; duplicateOf?: string }
export interface Feature { name: string; kind: "feature" | "fix"; supported: boolean; defaultVote: "yes" | "no" | "obsolete"; retired: boolean; order: number }
export interface TerCode { code: string; category: string; value: number; description?: string; comment?: string; unused: boolean }
export interface SField { name: string; type: string; nth: number; untyped: boolean; flags?: string }
export interface Permission { name: string; txType: string; value: number; allowedFlags: string[]; allowedFields: TxField[]; doc?: string }
export interface InnerObject { name: string; fields: TxField[] }

export interface Protocol {
  source: { version?: string; commit?: string; commitDate?: string; branch?: string; repo: string; extractedAt: string };
  transactions: Transaction[];
  txFlags: { byTx: Record<string, { flags: FlagDef[]; maskAdj: string[] }>; asf: FlagDef[]; universal: FlagDef[] };
  ledgerFlags: Record<string, FlagDef[]>;
  ledgerEntries: LedgerEntry[];
  features: Feature[];
  results: TerCode[];
  sfields: SField[];
  permissions: Permission[];
  innerObjects: InnerObject[];
  commonFields: TxField[];
}

export interface TestnetAmendment { id: string; name: string; enabled: boolean; supported: boolean; vetoed?: boolean | string; majority?: number; count?: number; threshold?: number; validations?: number }
export interface FieldDef { nth: number; type: string; isVLEncoded: boolean; isSerialized: boolean; isSigningField: boolean }
export interface Testnet {
  rpc: string;
  fetchedAt: string;
  buildVersion: string;
  networkId: number;
  validatedLedger: { seq: number; hash: string; base_fee_xrp: number; reserve_base_xrp: number; reserve_inc_xrp: number };
  completeLedgers: string;
  amendmentBlocked: boolean;
  reserves: { baseXrp: number; incXrp: number; baseFeeXrp: number; loadFactor: number };
  amendments: TestnetAmendment[];
  definitions: {
    hash: string;
    TYPES: Record<string, number>;
    FIELDS: Record<string, FieldDef>;
    TRANSACTION_TYPES: Record<string, number>;
    LEDGER_ENTRY_TYPES: Record<string, number>;
    TRANSACTION_RESULTS: Record<string, number>;
    TRANSACTION_FORMATS: Record<string, { name: string; optionality: number }[]>;
    LEDGER_ENTRY_FORMATS: Record<string, { name: string; optionality: number }[]>;
    TRANSACTION_FLAGS: Record<string, Record<string, number>>;
    ACCOUNT_SET_FLAGS: Record<string, number>;
    LEDGER_ENTRY_FLAGS: Record<string, Record<string, number>>;
  };
}

export const protocol = protocolJson as unknown as Protocol;
export const testnet = testnetJson as unknown as Testnet;

export const PSEUDO_TX = new Set(["EnableAmendment", "SetFee", "UNLModify"]);

/** Transaction names that exist in testnet's xrpld (alphabetical order). */
export function testnetTxNames(): string[] {
  return Object.keys(testnet.definitions.TRANSACTION_TYPES).filter((n) => n !== "Invalid").sort();
}

export function getTx(name: string): Transaction | undefined {
  return protocol.transactions.find((t) => t.name === name);
}

export function getLedgerEntry(name: string): LedgerEntry | undefined {
  return protocol.ledgerEntries.find((e) => e.name === name);
}

export function testnetLedgerEntryNames(): string[] {
  return Object.keys(testnet.definitions.LEDGER_ENTRY_TYPES).filter((n) => !["Invalid", "Any", "Child"].includes(n)).sort();
}

export function getField(name: string): (SField & { def?: FieldDef }) | undefined {
  const sf = protocol.sfields.find((s) => s.name === name);
  const def = testnet.definitions.FIELDS[name];
  if (!sf && !def) return undefined;
  return { name, type: sf?.type ?? def?.type ?? "?", nth: sf?.nth ?? def?.nth ?? 0, untyped: sf?.untyped ?? false, flags: sf?.flags, def };
}

/** JSON type (server_definitions naming) of a field: AccountID, Amount, UInt32, Blob… */
export function fieldType(name: string): string {
  return testnet.definitions.FIELDS[name]?.type ?? normalizeType(protocol.sfields.find((s) => s.name === name)?.type ?? "Unknown");
}

const TYPE_MAP: Record<string, string> = { ACCOUNT: "AccountID", AMOUNT: "Amount", UINT8: "UInt8", UINT16: "UInt16", UINT32: "UInt32", UINT64: "UInt64", INT32: "Int32", HASH128: "Hash128", HASH160: "Hash160", HASH192: "Hash192", HASH256: "Hash256", VL: "Blob", STARRAY: "STArray", STOBJECT: "STObject", PATHSET: "PathSet", VECTOR256: "Vector256", ISSUE: "Issue", CURRENCY: "Currency", NUMBER: "Number", XCHAIN_BRIDGE: "XChainBridge" };
export function normalizeType(t: string) {
  return TYPE_MAP[t] ?? t;
}

/**
 * Effective fields of a transaction on testnet, with source information
 * (MPT support, "default" optionality) and marking the ones that only exist in the source.
 */
export interface MergedField extends TxField { type: string; inTestnet: boolean; inSource: boolean; common: boolean }
export function mergedFields(name: string): MergedField[] {
  const src = getTx(name);
  const tn = testnet.definitions.TRANSACTION_FORMATS[name] ?? [];
  const out: MergedField[] = [];
  const seen = new Set<string>();
  for (const f of tn) {
    const s = src?.fields.find((x) => x.name === f.name);
    out.push({ name: f.name, optionality: s?.optionality ?? (f.optionality === 0 ? "required" : "optional"), mptSupported: s?.mptSupported ?? false, type: fieldType(f.name), inTestnet: true, inSource: !!s, common: false });
    seen.add(f.name);
  }
  for (const s of src?.fields ?? []) if (!seen.has(s.name)) out.push({ ...s, type: fieldType(s.name), inTestnet: false, inSource: true, common: false });
  return out;
}

export function commonFields(): MergedField[] {
  return protocol.commonFields.map((f) => ({ ...f, type: fieldType(f.name), inTestnet: true, inSource: true, common: true }));
}

/** Valid flags for a transaction according to testnet (with hex and source doc if it exists). */
export function txFlags(name: string): FlagDef[] {
  const tn = testnet.definitions.TRANSACTION_FLAGS[name] ?? {};
  const src = protocol.txFlags.byTx[name]?.flags ?? [];
  return Object.entries(tn).map(([n, v]) => ({ name: n, value: v, hex: "0x" + v.toString(16).padStart(8, "0"), doc: src.find((f) => f.name === n)?.doc }));
}

export function amendmentStatus(name: string): TestnetAmendment | undefined {
  return testnet.amendments.find((a) => a.name === name);
}

export function getFeature(name: string): Feature | undefined {
  return protocol.features.find((f) => f.name === name);
}

/** Converts `featureFoo` / `fixBar` (C++ identifiers) to the amendment name. */
export function featureIdToName(id: string): string {
  return id.startsWith("feature") ? id.slice(7) : id;
}

export function getResult(code: string): TerCode | undefined {
  return protocol.results.find((r) => r.code === code);
}

export const TER_CATEGORIES: Record<string, { label: string; meaning: string; claimsFee: boolean; applied: boolean }> = {
  tes: { label: "Success", meaning: "The transaction was applied to the ledger.", claimsFee: true, applied: true },
  tec: { label: "Failure with fee", meaning: "The transaction failed but was included in the ledger: it charges the fee and consumes the Sequence.", claimsFee: true, applied: true },
  tem: { label: "Malformed", meaning: "The transaction is badly constructed: it's never applied and never charges a fee.", claimsFee: false, applied: false },
  tef: { label: "Definitive failure", meaning: "It cannot be applied (for example, it was already applied before). No fee charged.", claimsFee: false, applied: false },
  tel: { label: "Local error", meaning: "The server that received it rejected it (full queue, insufficient fee…). Another server might accept it.", claimsFee: false, applied: false },
  ter: { label: "Retriable", meaning: "It cannot be applied yet (e.g. future Sequence). It's retried in subsequent ledgers.", claimsFee: false, applied: false },
};

/** GitHub URL for a source file at the exact extracted commit. */
export function sourceUrl(file: string, line?: number): string {
  const ref = protocol.source.commit ?? protocol.source.branch ?? "develop";
  return `${protocol.source.repo}/blob/${ref}/${file}${line ? `#L${line}` : ""}`;
}

/** Amendments the transactor checks in the code (rules.enabled(...)). */
export function txAmendments(t: Transaction): { name: string; status?: TestnetAmendment; gate: boolean }[] {
  const names = new Set<string>();
  if (t.amendment) names.add(t.amendment);
  for (const f of t.transactor?.allFeatures ?? []) names.add(featureIdToName(f));
  return [...names].sort().map((n) => ({ name: n, status: amendmentStatus(n), gate: n === t.amendment }));
}

/** Transactions that return a given TER (for "who can return tecNO_DST"). */
export function txReturning(code: string): string[] {
  return protocol.transactions.filter((t) => t.transactor?.allTer.includes(code)).map((t) => t.name);
}

/** Transactions and objects that use a field. */
export function fieldUsage(name: string) {
  return {
    transactions: protocol.transactions.filter((t) => t.fields.some((f) => f.name === name)).map((t) => t.name),
    ledgerEntries: protocol.ledgerEntries.filter((e) => e.fields.some((f) => f.name === name)).map((e) => e.name),
    innerObjects: protocol.innerObjects.filter((o) => o.fields.some((f) => f.name === name)).map((o) => o.name),
  };
}
