/**
 * Extracts protocol.json for every network's source version.
 * Output: src/data/protocol/<ref>.json (deduplicated by git ref) and writes `sourceRef` into each
 * network snapshot so the web knows which protocol file to use.
 *
 * Usage: pnpm extract:all [--update]  (--update refreshes develop)
 */
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { NETWORKS } from "../lib/networks";
import { sourceFor } from "../lib/source";

const ROOT = path.resolve(import.meta.dirname, "../..");
const update = process.argv.includes("--update");
const done = new Set<string>();
for (const net of NETWORKS) {
  const snapPath = path.join(ROOT, "src/data/networks", net.id, "snapshot.json");
  if (!fs.existsSync(snapPath)) { console.log(`${net.id}: no snapshot, skipping`); continue; }
  const snap = JSON.parse(fs.readFileSync(snapPath, "utf8"));
  const { dir, ref } = sourceFor(snap.buildVersion, update && !done.size);
  const out = path.join(ROOT, "src/data/protocol", `${ref.replace(/[^\w.-]/g, "_")}.json`);
  if (!done.has(ref)) {
    execSync(`pnpm exec tsx tools/extract/extract.ts --source ${JSON.stringify(dir)} --out ${JSON.stringify(out)}`, { cwd: ROOT, stdio: "inherit" });
    done.add(ref);
  }
  snap.sourceRef = ref.replace(/[^\w.-]/g, "_");
  fs.writeFileSync(snapPath, JSON.stringify(snap, null, 2));
  console.log(`${net.id}: ${snap.buildVersion} → source ${ref}`);
}
// Generated index consumed by the web (static imports).
const nets = NETWORKS.filter((n) => fs.existsSync(path.join(ROOT, "src/data/networks", n.id, "snapshot.json")));
const refs = [...new Set(nets.map((n) => JSON.parse(fs.readFileSync(path.join(ROOT, "src/data/networks", n.id, "snapshot.json"), "utf8")).sourceRef as string))];
const idx = [
  "// GENERATED by tools/extract/all.ts — do not edit.",
  ...nets.map((n, i) => `import snap${i} from "./networks/${n.id}/snapshot.json";`),
  ...refs.map((r, i) => `import proto${i} from "./protocol/${r}.json";`),
  `export const snapshots = { ${nets.map((n, i) => `"${n.id}": snap${i}`).join(", ")} } as const;`,
  `export const protocols = { ${refs.map((r, i) => `"${r}": proto${i}`).join(", ")} } as const;`,
  "",
].join("\n");
fs.writeFileSync(path.join(ROOT, "src/data/index.ts"), idx);
console.log(`index: ${nets.length} networks, ${refs.length} protocol refs`);
