// GENERATED by tools/extract/all.ts — do not edit.
import snap0 from "./networks/mainnet/snapshot.json";
import snap1 from "./networks/testnet/snapshot.json";
import snap2 from "./networks/devnet/snapshot.json";
import snap3 from "./networks/amm-devnet/snapshot.json";
import snap4 from "./networks/wasm-devnet/snapshot.json";
import proto0 from "./protocol/3.3.0.json";
import proto1 from "./protocol/develop.json";
export const snapshots = { "mainnet": snap0, "testnet": snap1, "devnet": snap2, "amm-devnet": snap3, "wasm-devnet": snap4 } as const;
export const protocols = { "3.3.0": proto0, "develop": proto1 } as const;
