// GENERATED by tools/extract/all.ts — do not edit.
import snap0 from "./networks/testnet/snapshot.json";
import snap1 from "./networks/devnet/snapshot.json";
import snap2 from "./networks/amm-devnet/snapshot.json";
import snap3 from "./networks/wasm-devnet/snapshot.json";
import proto0 from "./protocol/develop.json";
export const snapshots = { "testnet": snap0, "devnet": snap1, "amm-devnet": snap2, "wasm-devnet": snap3 } as const;
export const protocols = { "develop": proto0 } as const;
